AnimeListSite/Controllers/AnimesController.cs
using Application.CQRS.Anime.Queries;
using Application.CQRS.User.Queries;
using Application.Models;
using Domain.Models.User;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace AnimeListSite.Controllers
{
    public class AnimesController : Controller
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public AnimesController(IMediator mediator, UserManager<User> userManager)
		{
			_mediator = mediator;
			_userManager = userManager;
		}

		public async Task<IActionResult> AnimesAsync(string name) {
			var user = await _userManager.GetUserAsync(HttpContext.User);

			GetAnimesWithNameQuery query = new GetAnimesWithNameQuery { 
            Name = name,
            UserId = user.Id
            };

            List<AnimePageVM> animes = await _mediator.Send(query);

			return View("Base/AnimeList", animes);
		}

        [Authorize]
		public async Task<IActionResult> AnimeAsync(int id) {
			var user = await _userManager.GetUserAsync(HttpContext.User);

			GetAnimeWithIdWMQuery query = new GetAnimeWithIdWMQuery
            {
                AnimeId = id,
                UserId = user.Id
            };

            AnimeFullVM anime = await _mediator.Send(query);

            return View(anime);
        }

        [Authorize]
		public async Task<IActionResult> TopHundredAsync()
        {
			var user = await _userManager.GetUserAsync(HttpContext.User);

            GetTopHundredAnimesQuery query = new GetTopHundredAnimesQuery
            {
                UserId = user.Id
            };

            List<AnimePageVM> animes = await _mediator.Send(query);

            return View("Base/AnimeList", animes);
        }
    }
}

AnimeListSite/Controllers/UserController.cs
using Application.CQRS.User.Commands;
using Application.CQRS.User.Queries;
using Application.Models;
using Domain.Models.User;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace AnimeListSite.Controllers
{
	public class UserController : Controller
	{
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public UserController(IMediator mediator, UserManager<User> userManager)
		{
			_mediator = mediator;
			_userManager = userManager;
		}

		[Authorize]
		public async Task<IActionResult> BookmarksFirstAsync()
		{
			var user = await _userManager.GetUserAsync(HttpContext.User);

			GetFirstBookmarkQuery firstBookmarkQuery = new GetFirstBookmarkQuery
			{
				UserId = user.Id
			};

			var firstBookmark = await _mediator.Send(firstBookmarkQuery);

			GetAnimesFromBookmarkQuery animesToShow = new GetAnimesFromBookmarkQuery
			{
				UserId = user.Id,
				BookmarkName = firstBookmark.Title
			};

			var animes = await _mediator.Send(animesToShow);

			GetUserBookmarksQuery AllBookmarksQuery = new GetUserBookmarksQuery
			{
				UserId = user.Id
			};

			var allBookmarks = await _mediator.Send(AllBookmarksQuery);

			BookmarksWithAnimesVM vm = new BookmarksWithAnimesVM
			{
				Animes = animes,
				Bookmarks = allBookmarks
			};

			return View("Bookmarks", vm);
		}

		public async Task<IActionResult> BookmarksAsync(string bookmarkName) {
			var user = await _userManager.GetUserAsync(HttpContext.User);

			GetAnimesFromBookmarkQuery animesQuery = new GetAnimesFromBookmarkQuery
			{
				UserId = user.Id,
				BookmarkName = bookmarkName
			};

			var animes = await _mediator.Send(animesQuery);

			GetUserBookmarksQuery query = new GetUserBookmarksQuery
			{
				UserId = user.Id
			};

			var bookmarks = await _mediator.Send(query);

			BookmarksWithAnimesVM vm = new BookmarksWithAnimesVM
			{
				Animes = animes,
				Bookmarks = bookmarks
			};

			return View(vm);
		}

		[HttpPost]
		public async Task<IActionResult> AddRemoveFromBookmarkAsync(string bookmark, int animeId) {
			var user = await _userManager.GetUserAsync(HttpContext.User);

			IsAnimeInBookmarkQuery query = new IsAnimeInBookmarkQuery
			{
				AnimeId = animeId,
				UserId = user.Id,
				Bookmark = bookmark
			};

			bool isInBookmark = await _mediator.Send(query);

			IRequest<bool> command = null;

			if (!isInBookmark)
			{
				command = new AddToUserBookmarkCommand
				{
					AnimeId = animeId,
					UserId = user.Id,
					Bookmark = bookmark
				};

			}
			else { 
				command = new RemoveFromUserBookmarkCommand
				{
					AnimeId = animeId,
					UserId = user.Id,
					Bookmark = bookmark
				};
			}

			await _mediator.Send(command);

			return Ok();
		}

		[HttpPost]
		public async Task<IActionResult> RatingAsync(int value, int animeId) {
			var user = await _userManager.GetUserAsync(HttpContext.User);

			SetRatingCommand command = new SetRatingCommand { Rating = value,
				UserId = user.Id,
				AnimeId = animeId
			};

			await _mediator.Send(command);

			return Ok();
		}
	}
}

AnimeListSite/Views/Shared/Base/AnimeItem.cshtml
@using Application.Models
@model AnimePageVM

<link rel="stylesheet" href="~/css/anime-item.css" />

<div class="anime-item">
	<img src="@Model.Image.Original" id="anime-image" />
	<a asp-action="Anime" asp-controller="Animes" asp-route-id=@Model.Id  id="name">@Model.Name</a>
	<div id="rating-handler">
		<span id="middle-rating" class="rating">@Model.Score</span>
			@{
			@if (Model.UserRating != 0)
				{
				<span id="user-rating" class="rating">@Model.UserRating</span>
				} 
			}

	</div>
</div>

AnimeListSite/Views/Shared/Base/AnimeList.cshtml
@using Application.Models

<link rel="stylesheet" href="~/css/anime-list.css" />


@model ICollection<AnimePageVM>

<div id="animes-wrapper">
	@{
		foreach (var element in Model)
		{
			@await Html.PartialAsync("Base/AnimeItem", element)
		}
	}
</div>

AnimeListSite/Views/Shared/Base/Header.cshtml
<link rel="stylesheet" href="~/css/header.css" />

<header>
    <img src="~/Images/header_bg.png" id="header-img" />
    <div id="header-wrapper">
        <img src="~/Images/burger_icon.png" id="header-icon"/>


        <a href="#" class="button">Anime Burger </a>

        <a asp-action="TopHundred" asp-controller="Animes" class="button"><p>TOP</p></a>

        <form asp-action="Animes" asp-controller="Animes">
            <input  class="submit_on_enter" type="text" name="name" placeholder="Search..." id="search">
        </form>

        <div id="login-info">
            <a asp-action="BookmarksFirst" asp-controller="User" class="button">
                <img src="~/Images/folder-icon.png" class="user-icon" />
            </a>
            <partial name="_LoginPartial" />
        </div>
    </div>
</header>

<script>
    function handleKeyPress(event) {
        if (event.key === "Enter") {
            // Получаем значение из текстового поля
            var searchText = document.getElementById("search").value;

            // Формируем URL для перехода

            var url = "/Animes/Anime?name=" + encodeURIComponent(searchText);

            // Перенаправляем на новую страницу
            window.location.href = url;
        }
    }
</script>